// Équipes nationales : nom anglais (The Odds API) → code ISO (drapeaux) + nom français.

const TEAMS = [
    { code: "ar", fr: "Argentine", en: ["argentina"] },
    { code: "au", fr: "Australie", en: ["australia"] },
    { code: "at", fr: "Autriche", en: ["austria"] },
    { code: "be", fr: "Belgique", en: ["belgium"] },
    { code: "bo", fr: "Bolivie", en: ["bolivia"] },
    { code: "ba", fr: "Bosnie-Herzégovine", en: ["bosnia and herzegovina", "bosnia herzegovina", "bosnia", "bosniaherzegovina"] },
    { code: "br", fr: "Brésil", en: ["brazil"] },
    { code: "ca", fr: "Canada", en: ["canada"] },
    { code: "cv", fr: "Cap-Vert", en: ["cape verde", "cabo verde", "cape verde islands"] },
    { code: "cl", fr: "Chili", en: ["chile"] },
    { code: "co", fr: "Colombie", en: ["colombia"] },
    { code: "kr", fr: "Corée du Sud", en: ["south korea", "korea republic", "korea"] },
    { code: "cr", fr: "Costa Rica", en: ["costa rica"] },
    { code: "ci", fr: "Côte d'Ivoire", en: ["ivory coast", "cote divoire"] },
    { code: "hr", fr: "Croatie", en: ["croatia"] },
    { code: "cw", fr: "Curaçao", en: ["curacao"] },
    { code: "dk", fr: "Danemark", en: ["denmark"] },
    { code: "eg", fr: "Égypte", en: ["egypt"] },
    { code: "ec", fr: "Équateur", en: ["ecuador"] },
    { code: "es", fr: "Espagne", en: ["spain"] },
    { code: "us", fr: "États-Unis", en: ["usa", "united states", "united states of america"] },
    { code: "fr", fr: "France", en: ["france"] },
    { code: "gh", fr: "Ghana", en: ["ghana"] },
    { code: "gr", fr: "Grèce", en: ["greece"] },
    { code: "ht", fr: "Haïti", en: ["haiti"] },
    { code: "hn", fr: "Honduras", en: ["honduras"] },
    { code: "hu", fr: "Hongrie", en: ["hungary"] },
    { code: "id", fr: "Indonésie", en: ["indonesia"] },
    { code: "iq", fr: "Irak", en: ["iraq"] },
    { code: "ir", fr: "Iran", en: ["iran", "ir iran"] },
    { code: "ie", fr: "Irlande", en: ["ireland", "republic of ireland"] },
    { code: "it", fr: "Italie", en: ["italy"] },
    { code: "jm", fr: "Jamaïque", en: ["jamaica"] },
    { code: "jp", fr: "Japon", en: ["japan"] },
    { code: "jo", fr: "Jordanie", en: ["jordan"] },
    { code: "xk", fr: "Kosovo", en: ["kosovo"] },
    { code: "mk", fr: "Macédoine du Nord", en: ["north macedonia", "macedonia"] },
    { code: "ma", fr: "Maroc", en: ["morocco"] },
    { code: "mx", fr: "Mexique", en: ["mexico"] },
    { code: "nc", fr: "Nouvelle-Calédonie", en: ["new caledonia"] },
    { code: "nz", fr: "Nouvelle-Zélande", en: ["new zealand"] },
    { code: "ng", fr: "Nigeria", en: ["nigeria"] },
    { code: "no", fr: "Norvège", en: ["norway"] },
    { code: "om", fr: "Oman", en: ["oman"] },
    { code: "uz", fr: "Ouzbékistan", en: ["uzbekistan"] },
    { code: "pa", fr: "Panama", en: ["panama"] },
    { code: "py", fr: "Paraguay", en: ["paraguay"] },
    { code: "nl", fr: "Pays-Bas", en: ["netherlands", "holland"] },
    { code: "pe", fr: "Pérou", en: ["peru"] },
    { code: "pl", fr: "Pologne", en: ["poland"] },
    { code: "pt", fr: "Portugal", en: ["portugal"] },
    { code: "qa", fr: "Qatar", en: ["qatar"] },
    { code: "cd", fr: "RD Congo", en: ["dr congo", "democratic republic of the congo", "congo dr"] },
    { code: "ro", fr: "Roumanie", en: ["romania"] },
    { code: "rs", fr: "Serbie", en: ["serbia"] },
    { code: "sk", fr: "Slovaquie", en: ["slovakia"] },
    { code: "si", fr: "Slovénie", en: ["slovenia"] },
    { code: "sn", fr: "Sénégal", en: ["senegal"] },
    { code: "sa", fr: "Arabie saoudite", en: ["saudi arabia"] },
    { code: "za", fr: "Afrique du Sud", en: ["south africa"] },
    { code: "se", fr: "Suède", en: ["sweden"] },
    { code: "ch", fr: "Suisse", en: ["switzerland"] },
    { code: "sr", fr: "Suriname", en: ["suriname"] },
    { code: "cz", fr: "Tchéquie", en: ["czech republic", "czechia"] },
    { code: "tn", fr: "Tunisie", en: ["tunisia"] },
    { code: "tr", fr: "Turquie", en: ["turkey", "turkiye"] },
    { code: "ua", fr: "Ukraine", en: ["ukraine"] },
    { code: "uy", fr: "Uruguay", en: ["uruguay"] },
    { code: "ve", fr: "Venezuela", en: ["venezuela"] },
    { code: "al", fr: "Albanie", en: ["albania"] },
    { code: "dz", fr: "Algérie", en: ["algeria"] },
    { code: "de", fr: "Allemagne", en: ["germany"] },
    { code: "gb-eng", fr: "Angleterre", en: ["england"] },
    { code: "gb-sct", fr: "Écosse", en: ["scotland"] },
    { code: "gb-wls", fr: "Pays de Galles", en: ["wales"] },
    { code: "gb-nir", fr: "Irlande du Nord", en: ["northern ireland"] },
    { code: "cm", fr: "Cameroun", en: ["cameroon"] },
    { code: "ml", fr: "Mali", en: ["mali"] },
    { code: "bf", fr: "Burkina Faso", en: ["burkina faso"] },
    { code: "gn", fr: "Guinée", en: ["guinea"] },
    { code: "ga", fr: "Gabon", en: ["gabon"] },
    { code: "ug", fr: "Ouganda", en: ["uganda"] },
    { code: "ae", fr: "Émirats arabes unis", en: ["united arab emirates", "uae"] },
    { code: "kw", fr: "Koweït", en: ["kuwait"] },
    { code: "bh", fr: "Bahreïn", en: ["bahrain"] },
    { code: "cn", fr: "Chine", en: ["china", "china pr"] },
    { code: "in", fr: "Inde", en: ["india"] },
    { code: "th", fr: "Thaïlande", en: ["thailand"] },
    { code: "vn", fr: "Vietnam", en: ["vietnam"] },
    { code: "fj", fr: "Fidji", en: ["fiji"] },
    { code: "ph", fr: "Philippines", en: ["philippines"] },
    { code: "ru", fr: "Russie", en: ["russia"] },
    { code: "il", fr: "Israël", en: ["israel"] },
    { code: "ge", fr: "Géorgie", en: ["georgia"] },
    { code: "am", fr: "Arménie", en: ["armenia"] },
    { code: "by", fr: "Biélorussie", en: ["belarus"] },
    { code: "bg", fr: "Bulgarie", en: ["bulgaria"] },
    { code: "cy", fr: "Chypre", en: ["cyprus"] },
    { code: "ee", fr: "Estonie", en: ["estonia"] },
    { code: "fi", fr: "Finlande", en: ["finland"] },
    { code: "is", fr: "Islande", en: ["iceland"] },
    { code: "lv", fr: "Lettonie", en: ["latvia"] },
    { code: "lt", fr: "Lituanie", en: ["lithuania"] },
    { code: "lu", fr: "Luxembourg", en: ["luxembourg"] },
    { code: "mt", fr: "Malte", en: ["malta"] },
    { code: "md", fr: "Moldavie", en: ["moldova"] },
    { code: "me", fr: "Monténégro", en: ["montenegro"] },
    { code: "sv", fr: "Salvador", en: ["el salvador"] },
    { code: "gt", fr: "Guatemala", en: ["guatemala"] },
    { code: "tt", fr: "Trinité-et-Tobago", en: ["trinidad and tobago"] },
];

// Même slug que côté client : identifiant de prédiction "jour-domicile-exterieur"
export const slug = (s) =>
    String(s).normalize("NFD").replace(/[^a-zA-Z0-9]/g, "").toLowerCase();

export const normalizeName = (s) =>
    String(s || "")
        .normalize("NFD")
        .replace(/[̀-ͯ]/g, "")
        .replace(/[^a-zA-Z ]/g, "")
        .replace(/\s+/g, " ")
        .trim()
        .toLowerCase();

const INDEX = new Map();
for (const t of TEAMS) for (const name of t.en) INDEX.set(name, t);

// → {code, fr} ; repli sur le nom anglais si l'équipe est inconnue
export function teamInfo(englishName) {
    const t = INDEX.get(normalizeName(englishName));
    return t ? { code: t.code, fr: t.fr } : { code: null, fr: String(englishName || "?") };
}
